// bus事件
module.exports = {
  CUSTOMER_LIST_REFLUSH: 'CUSTOMER_LIST_REFLUSH', //客户信息列表刷新
  CUSTOMER_CHANNEL_OFFER_APPLY_REFLUSH: 'CUSTOMER_CHANNEL_OFFER_APPLY_REFLUSH', //渠道报价信息列表刷新
  CUSTOMER_VISITING_PLAN_REFLUSH: 'CUSTOMER_VISITING_PLAN_REFLUSH', //客户拜访计划信息列表刷新
  SHOP_DETAIL_REFRESH: 'SHOP_DETAIL_REFRESH', // 店铺列表刷新
  SHOP_LIST_REFRESH: 'SHOP_LIST_REFRESH', // 店铺列表刷新
}